# Generated by Django 3.2.9 on 2021-11-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptp', '0002_persona_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
